blank_issues_enabled: false
contact_links:
  - name: Community Discord
    url: https://discord.gg/W79wD5wUjx
    about: Please ask and answer questions here before creating an issue if you're unsure.
